/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsCreateRouteImport } from './routes/markets.create'
import { Route as MarketsIdRouteImport } from './routes/markets.$id'

const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsCreateRoute = MarketsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRoute
  '/markets': typeof MarketsRouteWithChildren
  '/simulate': typeof SimulateRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRoute
  '/simulate': typeof SimulateRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRoute
  '/markets': typeof MarketsRouteWithChildren
  '/simulate': typeof SimulateRoute
  '/markets/$id': typeof MarketsIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/explorer'
    | '/markets'
    | '/simulate'
    | '/markets/$id'
    | '/markets/create'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs'
    | '/explorer'
    | '/simulate'
    | '/markets/$id'
    | '/markets/create'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs'
    | '/explorer'
    | '/markets'
    | '/simulate'
    | '/markets/$id'
    | '/markets/create'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  ExplorerRoute: typeof ExplorerRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  SimulateRoute: typeof SimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/create': {
      id: '/markets/create'
      path: '/create'
      fullPath: '/markets/create'
      preLoaderRoute: typeof MarketsCreateRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$id': {
      id: '/markets/$id'
      path: '/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof MarketsRoute
    }
  }
}

interface MarketsRouteChildren {
  MarketsIdRoute: typeof MarketsIdRoute
  MarketsCreateRoute: typeof MarketsCreateRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsIdRoute: MarketsIdRoute,
  MarketsCreateRoute: MarketsCreateRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  ExplorerRoute: ExplorerRoute,
  MarketsRoute: MarketsRouteWithChildren,
  SimulateRoute: SimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
